'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.36388
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6172.1$钢六角薄螺母")>  _
        Public Property XH002() As String
            Get
                Return CType(Me("XH002"),String)
            End Get
            Set
                Me("XH002") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB11263$H型钢")>  _
        Public Property XH003() As String
            Get
                Return CType(Me("XH003"),String)
            End Get
            Set
                Me("XH003") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB119.1$圆柱销")>  _
        Public Property XH004() As String
            Get
                Return CType(Me("XH004"),String)
            End Get
            Set
                Me("XH004") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB12618$抽芯铆钉")>  _
        Public Property XH005() As String
            Get
                Return CType(Me("XH005"),String)
            End Get
            Set
                Me("XH005") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB819.1$十字槽沉头螺钉")>  _
        Public Property XH006() As String
            Get
                Return CType(Me("XH006"),String)
            End Get
            Set
                Me("XH006") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB861.1$锁紧垫圈")>  _
        Public Property XH007() As String
            Get
                Return CType(Me("XH007"),String)
            End Get
            Set
                Me("XH007") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB902.1$焊接螺柱")>  _
        Public Property XH008() As String
            Get
                Return CType(Me("XH008"),String)
            End Get
            Set
                Me("XH008") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HG20610$缠绕垫片")>  _
        Public Property XH009() As String
            Get
                Return CType(Me("XH009"),String)
            End Get
            Set
                Me("XH009") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6175$钢六角螺母")>  _
        Public Property XH010() As String
            Get
                Return CType(Me("XH010"),String)
            End Get
            Set
                Me("XH010") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB1096$平键")>  _
        Public Property XH011() As String
            Get
                Return CType(Me("XH011"),String)
            End Get
            Set
                Me("XH011") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB2028$船用放泄螺塞")>  _
        Public Property XH012() As String
            Get
                Return CType(Me("XH012"),String)
            End Get
            Set
                Me("XH012") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB3009$防蚀螺塞")>  _
        Public Property XH013() As String
            Get
                Return CType(Me("XH013"),String)
            End Get
            Set
                Me("XH013") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB4622.2$缠绕垫片")>  _
        Public Property XH014() As String
            Get
                Return CType(Me("XH014"),String)
            End Get
            Set
                Me("XH014") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5780$钢六角螺栓")>  _
        Public Property XH015() As String
            Get
                Return CType(Me("XH015"),String)
            End Get
            Set
                Me("XH015") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5781$钢六角螺栓")>  _
        Public Property XH016() As String
            Get
                Return CType(Me("XH016"),String)
            End Get
            Set
                Me("XH016") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5782$钢六角螺栓")>  _
        Public Property XH017() As String
            Get
                Return CType(Me("XH017"),String)
            End Get
            Set
                Me("XH017") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5783$钢六角螺栓")>  _
        Public Property XH018() As String
            Get
                Return CType(Me("XH018"),String)
            End Get
            Set
                Me("XH018") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5785$钢六角螺栓")>  _
        Public Property XH019() As String
            Get
                Return CType(Me("XH019"),String)
            End Get
            Set
                Me("XH019") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB5786$钢六角螺栓")>  _
        Public Property XH020() As String
            Get
                Return CType(Me("XH020"),String)
            End Get
            Set
                Me("XH020") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6170$钢六角螺母")>  _
        Public Property XH021() As String
            Get
                Return CType(Me("XH021"),String)
            End Get
            Set
                Me("XH021") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6171$钢六角螺母")>  _
        Public Property XH022() As String
            Get
                Return CType(Me("XH022"),String)
            End Get
            Set
                Me("XH022") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6175$钢六角螺母")>  _
        Public Property XH023() As String
            Get
                Return CType(Me("XH023"),String)
            End Get
            Set
                Me("XH023") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB6184$锁紧螺母")>  _
        Public Property XH024() As String
            Get
                Return CType(Me("XH024"),String)
            End Get
            Set
                Me("XH024") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB70.1$钢内六角圆柱头螺钉")>  _
        Public Property XH025() As String
            Get
                Return CType(Me("XH025"),String)
            End Get
            Set
                Me("XH025") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB9115$法兰")>  _
        Public Property XH026() As String
            Get
                Return CType(Me("XH026"),String)
            End Get
            Set
                Me("XH026") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB9119$法兰")>  _
        Public Property XH027() As String
            Get
                Return CType(Me("XH027"),String)
            End Get
            Set
                Me("XH027") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB97.1$钢平垫圈")>  _
        Public Property XH028() As String
            Get
                Return CType(Me("XH028"),String)
            End Get
            Set
                Me("XH028") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB97.2$钢平垫圈")>  _
        Public Property XH029() As String
            Get
                Return CType(Me("XH029"),String)
            End Get
            Set
                Me("XH029") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB97.3$钢平垫圈")>  _
        Public Property XH030() As String
            Get
                Return CType(Me("XH030"),String)
            End Get
            Set
                Me("XH030") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB100$开槽沉头木螺钉")>  _
        Public Property XH031() As String
            Get
                Return CType(Me("XH031"),String)
            End Get
            Set
                Me("XH031") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB116$铆钉")>  _
        Public Property XH032() As String
            Get
                Return CType(Me("XH032"),String)
            End Get
            Set
                Me("XH032") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB117$圆锥销")>  _
        Public Property XH033() As String
            Get
                Return CType(Me("XH033"),String)
            End Get
            Set
                Me("XH033") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB575$船用铜法兰")>  _
        Public Property XH034() As String
            Get
                Return CType(Me("XH034"),String)
            End Get
            Set
                Me("XH034") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB798$钢六角螺栓")>  _
        Public Property XH035() As String
            Get
                Return CType(Me("XH035"),String)
            End Get
            Set
                Me("XH035") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB799$地脚螺栓")>  _
        Public Property XH036() As String
            Get
                Return CType(Me("XH036"),String)
            End Get
            Set
                Me("XH036") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB812$圆螺母")>  _
        Public Property XH037() As String
            Get
                Return CType(Me("XH037"),String)
            End Get
            Set
                Me("XH037") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB818$十字槽盘头螺钉")>  _
        Public Property XH038() As String
            Get
                Return CType(Me("XH038"),String)
            End Get
            Set
                Me("XH038") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB822$十字槽圆柱头螺钉")>  _
        Public Property XH039() As String
            Get
                Return CType(Me("XH039"),String)
            End Get
            Set
                Me("XH039") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB825$吊环螺钉")>  _
        Public Property XH040() As String
            Get
                Return CType(Me("XH040"),String)
            End Get
            Set
                Me("XH040") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB827$标牌铆钉")>  _
        Public Property XH041() As String
            Get
                Return CType(Me("XH041"),String)
            End Get
            Set
                Me("XH041") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB845$十字槽盘头自攻螺钉")>  _
        Public Property XH042() As String
            Get
                Return CType(Me("XH042"),String)
            End Get
            Set
                Me("XH042") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB848$小垫圈")>  _
        Public Property XH043() As String
            Get
                Return CType(Me("XH043"),String)
            End Get
            Set
                Me("XH043") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB852$工钢用方斜垫圈")>  _
        Public Property XH044() As String
            Get
                Return CType(Me("XH044"),String)
            End Get
            Set
                Me("XH044") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB853$槽钢用方斜垫圈")>  _
        Public Property XH045() As String
            Get
                Return CType(Me("XH045"),String)
            End Get
            Set
                Me("XH045") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB854$单耳止动垫圈")>  _
        Public Property XH046() As String
            Get
                Return CType(Me("XH046"),String)
            End Get
            Set
                Me("XH046") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB858$圆螺母用止动垫圈")>  _
        Public Property XH047() As String
            Get
                Return CType(Me("XH047"),String)
            End Get
            Set
                Me("XH047") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB866$沉头铆钉")>  _
        Public Property XH048() As String
            Get
                Return CType(Me("XH048"),String)
            End Get
            Set
                Me("XH048") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB867$半圆头铆钉")>  _
        Public Property XH049() As String
            Get
                Return CType(Me("XH049"),String)
            End Get
            Set
                Me("XH049") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB872$扁平头铆钉")>  _
        Public Property XH050() As String
            Get
                Return CType(Me("XH050"),String)
            End Get
            Set
                Me("XH050") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB873$空心铆钉")>  _
        Public Property XH051() As String
            Get
                Return CType(Me("XH051"),String)
            End Get
            Set
                Me("XH051") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB880$带孔销")>  _
        Public Property XH052() As String
            Get
                Return CType(Me("XH052"),String)
            End Get
            Set
                Me("XH052") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB882$销轴")>  _
        Public Property XH053() As String
            Get
                Return CType(Me("XH053"),String)
            End Get
            Set
                Me("XH053") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB897$双头螺柱")>  _
        Public Property XH054() As String
            Get
                Return CType(Me("XH054"),String)
            End Get
            Set
                Me("XH054") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB898$双头螺柱")>  _
        Public Property XH055() As String
            Get
                Return CType(Me("XH055"),String)
            End Get
            Set
                Me("XH055") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB900$双头螺柱")>  _
        Public Property XH056() As String
            Get
                Return CType(Me("XH056"),String)
            End Get
            Set
                Me("XH056") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB901$等长双头螺柱")>  _
        Public Property XH057() As String
            Get
                Return CType(Me("XH057"),String)
            End Get
            Set
                Me("XH057") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB953$等长双头螺柱")>  _
        Public Property XH058() As String
            Get
                Return CType(Me("XH058"),String)
            End Get
            Set
                Me("XH058") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB41$钢六角螺母")>  _
        Public Property XH059() As String
            Get
                Return CType(Me("XH059"),String)
            End Get
            Set
                Me("XH059") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB56$钢六角厚螺母")>  _
        Public Property XH060() As String
            Get
                Return CType(Me("XH060"),String)
            End Get
            Set
                Me("XH060") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB65$钢开槽圆柱头螺钉")>  _
        Public Property XH061() As String
            Get
                Return CType(Me("XH061"),String)
            End Get
            Set
                Me("XH061") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB67$钢开槽盘头螺钉")>  _
        Public Property XH062() As String
            Get
                Return CType(Me("XH062"),String)
            End Get
            Set
                Me("XH062") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB68$钢开槽沉头螺钉")>  _
        Public Property XH063() As String
            Get
                Return CType(Me("XH063"),String)
            End Get
            Set
                Me("XH063") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB71$钢开槽锥端紧定螺钉")>  _
        Public Property XH064() As String
            Get
                Return CType(Me("XH064"),String)
            End Get
            Set
                Me("XH064") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB73$钢开槽平端紧定螺钉")>  _
        Public Property XH065() As String
            Get
                Return CType(Me("XH065"),String)
            End Get
            Set
                Me("XH065") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB75$钢方头长圆柱端紧定螺钉")>  _
        Public Property XH066() As String
            Get
                Return CType(Me("XH066"),String)
            End Get
            Set
                Me("XH066") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB85$螺钉")>  _
        Public Property XH067() As String
            Get
                Return CType(Me("XH067"),String)
            End Get
            Set
                Me("XH067") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB91$开口销")>  _
        Public Property XH068() As String
            Get
                Return CType(Me("XH068"),String)
            End Get
            Set
                Me("XH068") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB93$标准型弹簧垫圈")>  _
        Public Property XH069() As String
            Get
                Return CType(Me("XH069"),String)
            End Get
            Set
                Me("XH069") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB95$钢平垫圈")>  _
        Public Property XH070() As String
            Get
                Return CType(Me("XH070"),String)
            End Get
            Set
                Me("XH070") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("JB87$垫片")>  _
        Public Property XH071() As String
            Get
                Return CType(Me("XH071"),String)
            End Get
            Set
                Me("XH071") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("JB88$垫片")>  _
        Public Property XH072() As String
            Get
                Return CType(Me("XH072"),String)
            End Get
            Set
                Me("XH072") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GB4622.1$缠绕垫片")>  _
        Public Property XH073() As String
            Get
                Return CType(Me("XH073"),String)
            End Get
            Set
                Me("XH073") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My.MySettings
            Get
                Return Global.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
